project:
  type: website

website:
  title: "Lucas Pontes"
  favicon: assets/lucas/img/logo_transparent.png
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Lucas Pontes. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
  navbar:
    background: primary
    logo: assets/lucas/img/logo_transparent.png
    right:
      - text: BLOG
        href: posts/index.qmd
      - text: About
        href: about.qmd
      - icon: github
        text: GitHub
        href: https://github.com/LPontes
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/lucasmpontes/
format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual